#!/bin/bash
# Move specified to the seed directory and symlink those back to the current directory
# This was made for seeding files when using transmission

# location of the actual file to be seeded, which the symlinks will point to
seed_dir=~/torrents/seeds/
# location where transmission stores finished torrents, which is where the symlinks will be
dest_dir=~/torrents/downloads/

for file in "$@"; do
  mv "$file" "$seed_dir"
  ln -s "$seed_dir/$file" "$dest_dir"
done
