#!/bin/bash

main_monitor="$(xrandr -q | grep "\sconnected" | cut -d' ' -f1 | grep -v LVDS | head -n 1)"
new_monitor=$(xrandr -q | grep "\sconnected" | cut -d' ' -f1 | dmenu -i -p "Select monitor")

if [[ "$main_monitor" != "$new_monitor" ]]; then
	notify-send 'Casting'
	xrandr --output "$new_monitor" --same-as "$main_monitor"
else
	notify-send 'Resetting main monitor'
	xrandr --output "$main_monitor" --mode "$(xdpyinfo | grep dimensions | awk '{print $2}')"
fi
