#!/bin/bash

if [ $# -eq 1 ]; then
  count="$1"
else
  ((count = 60))
fi

while [[ $count -ne 0 ]] ; do
    ping -c 1 8.8.8.8
    rc=$?
    if [[ $rc -eq 0 ]] ; then
        ((count = 1))
    else
        sleep 1                          # Minimise network storm.
    fi
    ((count = count - 1))
done

if [[ $rc -eq 0 ]] ; then                # Make final determination.
  notify-send "Internet back up"
else
  notify-send "Internet god is dead"
fi
