#!/bin/bash

set -e

print_help() {
  echo -e "Usage: $(basename "$0") -u=URL -t=TITLE [-a=ARTIST] [-A=ALBUM] [-n=TRACKNUM] [-b=ALBUM_ARTIST]" >&2
  return 1
}

url=""
title=""
artist=""
album=""
tracknum=0
album_artist=""

for i in "$@"; do
  case "$i" in
  -u=*) url="${i#*=}" ;;
  -t=*) title="${i#*=}" ;;
  -a=*) artist="${i#*=}" ;;
  -A=*) album="${i#*=}" ;;
  -n=*) tracknum="${i#*=}" ;;
  -b=*) album_artist="${i#*=}" ;;
  *) print_help ;;
  esac
done

if [ "$url" = "" ] || [ "$title" = "" ]; then
  print_help
elif [ "$artist" = "" ]; then
  filename="$title"
else
  filename="${title} - ${artist}"
fi

# translate bad characters
filename="$(echo "$filename" | tr '<>:/\|?*' '_' | tr '"' "'")"

if [ "$tracknum" = "" ]; then
  tracknum=0
fi

if [ "$album_artist" = "" ] && [ "$album" != "" ] && [ "$artist" != "" ]; then
  album_artist="$artist"
fi

yt-dlp --no-playlist --extract-audio --audio-format mp3 "$url" -o "${filename}.mp3"

# audacity rewrites comments and deletes URL frames, only --user-text-frame kinda stays though its description also gets changed to TXXX
eyeD3 "${filename}.mp3" -t "$title" -a "$artist" -A "$album" -b "$album_artist" -n "$tracknum" --url-frame "WOAS:$url" --user-text-frame "URL:$url"
