#!/usr/bin/python3

import sys
import eyed3


def retag_from_filename(files: list[str]) -> None:
    for file in files:
        if file.endswith(".mp3"):
            try:
                _f = eyed3.load(file)
                arr = file[:-4].split(" - ")
                if len(arr) > 1:
                    _f.tag.artist = arr[-1]
                else:
                    print(f"[!] File {file} doesn't have an artist", file=sys.stderr)
                _f.tag.title = " - ".join(arr[:-1])
                _f.tag.save()
            except Exception as _e:
                print(f"[!] File {file} couldn't be retagged: {str(_e)}", file=sys.stderr)
        else:
            print(f"[!] File {file} is not an mp3 file", file=sys.stderr)


if __name__ == "__main__":
    retag_from_filename(sys.argv[1:])
