#!/bin/bash

# File format:
#
# .u URL            <- set source URL
# .t TITLE          <- set title
# .a ARTIST         <- set artist (optional)
# .A ALBUM          <- set album (optional)
# .Aa ALBUM_ARTIST  <- set album artist (optional)
# .n TRACK_NUM      <- set track number (optional)
# .dl               <- start/queue download with set parameters
#
# Note: All params except `.dl` need a space after them

group='music'
dest="$HOME/Downloads/music"
curr=0
url=
title=
artist=
album=
album_artist=
tracknum=

if [ $# -ne 1 ]; then
  echo "Usage: yt-to-mp3 SONGS_FILE" >&2
  exit 1
fi

if [ ! -e "$1" ]; then
  echo "[!] File '$1' does not exist" >&2
  exit 1
fi

while read -r line; do
  ((curr += 1))
  if [[ "$line" =~ ^'.u '.* ]]; then
    url="$(echo "$line" | cut -d ' ' -f 2-)"
  elif [[ "$line" =~ ^'.t '.* ]]; then
    title="$(echo "$line" | cut -d ' ' -f 2- | esc-sh)"
  elif [[ "$line" =~ ^'.a '.* ]]; then
    artist="$(echo "$line" | cut -d ' ' -f 2- | esc-sh)"
  elif [[ "$line" =~ ^'.A '.* ]]; then
    album="$(echo "$line" | cut -d ' ' -f 2- | esc-sh)"
  elif [[ "$line" =~ ^'.Aa '.* ]] || [[ "$line" =~ ^'.b '.* ]]; then
    album_artist="$(echo "$line" | cut -d ' ' -f 2- | esc-sh)"
  elif [[ "$line" =~ ^'.n '.* ]]; then
    tracknum="$(echo "$line" | cut -d ' ' -f 2- | esc-sh)"
  elif [[ "$line" =~ ^'.dl' ]]; then
    if [ "$url" = "" ] || [ "$title" = "" ]; then
      echo "[!] Error on line ${curr}:" >&2
      echo "[!] Missing URL or title" >&2
      exit 1
    else
      pueue add -g "$group" -w "$dest" -- dl-song -u="'$url'" -t="$title" -a="$artist" -A="$album" -n="$tracknum" -b="$album_artist" && echo "Enqueued: ${title} - ${artist}"
    fi
    url=
    title=
    artist=
    album=
    tracknum=
    album_artist=
  fi
done < "$1"

if [ "$url" != "" ]; then
  echo '[!] Did you forget a ".dl" before EOF?' >&2
  exit 1
fi
