#!/bin/bash

# File format:
#
# .u URL        <- set source URL
# .t TITLE      <- set title
# .a ARTIST     <- set artist (optional)
# .dl           <- start/queue download with set parameters
#
# Note: u, t, and a need a space after each. dl doesn't

group='music'
dest="$HOME/Downloads/music"
curr=0
url=
title=
artist=

if [ $# -ne 1 ]; then
  echo "Usage: yt-to-mp3 SONGS_FILE" >&2
  exit 1
fi

if [ ! -e "$1" ]; then
  echo "[!] File '$1' does not exist" >&2
  exit 1
fi

while read -r line; do
  ((curr += 1))
  if [[ "$line" =~ ^".u ".* ]]; then
    url="$(echo "$line" | cut -c 4-)"
  elif [[ "$line" =~ ^".t ".* ]]; then
    title="$(echo "$line" | cut -c 4- | esc_sh )"
  elif [[ "$line" =~ ^".a ".* ]]; then
    artist="$(echo "$line" | cut -c 4- | esc_sh )"
  elif [[ "$line" =~ ^".dl" ]]; then
    if [ "$url" = "" ] || [ "$title" = "" ]; then
      echo "[!] Error on line ${curr}:" >&2
      echo "[!] Missing URL or title" >&2
      exit 1
    elif [ "$artist" = "" ]; then
      pueue add -g "$group" -w "$dest" -- dl-song "'$url'" "$title" && echo "Enqueued: ${title}"
    else
      pueue add -g "$group" -w "$dest" -- dl-song "'$url'" "$title" "$artist" && echo "Enqueued: ${title}"
      artist=
    fi
    url=
    title=
  fi
done < "$1"

if [ "${url}" != "" ]; then
  echo '[!] Did you forget a ".dl" before EOF?' >&2
  exit 1
fi
