#!/bin/sh

files=$(ripdrag -d -t -x)

for file in $files
do
  path=${file#file://}
  name=$(basename "$path")
  case "$1" in
    mv) mv "$path" "$(pwd)/$name";;
    cp) cp "$path" "$(pwd)/$name";;
    *) echo "Invalid action";;
  esac
done
