#!/bin/bash

if [[ $# -eq 0 ]]; then
  orientation=$(echo -e "\
0) normal
1) left
2) right
3) inverted
" | rofi -dmenu -l 4 -theme-str 'window {width: 15%;}' -p "[$(hostname)] Rotate screen" | cut -d ' ' -f 2)
elif [[ $# -eq 1 ]]; then
  orientation="$1"
else
  echo "Too many arguments! ($#)" >&2
  echo "Usage: $(basename "$0") [orientation]" >&2
  exit 1
fi

monitor="$(bspc query --monitors --names | grep -v LVDS | head -n 1)"
xrandr --output "$monitor" --rotate "$orientation"
