#!/usr/bin/python3
import sys
import urllib.parse

if len(sys.argv) == 1:
    # url decode stdin
    for line in sys.stdin:
        print(urllib.parse.unquote_plus(line), end="")
else:
    # url decode args
    for i in sys.argv[1:]:
        print(urllib.parse.unquote_plus(i), end="")
