#!/usr/bin/python3
"""
Usage:
    urlencode [-a] some_string...
    urlencode [-a] < file
"""
import sys
import urllib.parse


def url_encode_all(string):
    """URL-encode *all* characters in a string"""
    return "".join(f"%{format(ord(char), 'x'):0>2}" for char in string)


if __name__ == "__main__":
    if len(sys.argv) == 1:
        # stdin
        for i in sys.stdin:
            print(urllib.parse.quote_plus(i), end="")
    elif len(sys.argv) == 2 and sys.argv[1] == "-a":
        # url encode all chars of stdin
        print(url_encode_all("".join(i for i in sys.stdin)), end="")
    elif sys.argv[1] == "-a":
        # url encode all chars of args
        for i in sys.argv[2:]:
            print(url_encode_all(i))
    else:
        # url encode args
        for i in sys.argv[1:]:
            print(urllib.parse.quote_plus(i))
